services:
  tinyproxy:
    image: vimagick/tinyproxy:latest
    container_name: tinyproxy
    ports:
      - "${HOST_IP}:8888:8888"
    environment:
      - DNS_SERVERS=${DNS_SERVERS}
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
    volumes:
      - ./data:/etc/tinyproxy
    entrypoint: ["/bin/sh", "/etc/tinyproxy/entrypoint.sh"]
