services:
  tinyproxy:
    image: vimagick/tinyproxy:latest
    container_name: tinyproxy
    ports:
      - "127.0.0.1:8888:8888"
    environment:
      - BASIC_AUTH_USER=${PROXY_USER:-admin}
      - BASIC_AUTH_PASSWORD=${PROXY_PASS}
      - DNS_SERVERS=${DNS_SERVERS:-83.220.169.155,212.109.195.93}
    volumes:
      - ./data:/etc/tinyproxy
    entrypoint: ["/bin/sh", "/etc/tinyproxy/entrypoint.sh"]

  
