services:
  tinyproxy:
    image: kalaksi/tinyproxy
    container_name: tinyproxy
    ports:
      - "${HOST_IP}:8888:8888"
    dns:
      - "83.220.169.155"
      - "212.109.195.93"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
